### ISSUE TITLE
add new TextFieldType members

### ISSUE THREAD

**Issue by ikliashchou** [regulaforensics/DocumentReader-web-openapi#36]
ft_Date_of_Insurance_Expiry = 596,
        ft_Mortgage_by = 597,
        ft_Old_Document_Number = 598,
        ft_Old_Date_of_Issue = 599,
        ft_Old_Place_of_Issue = 600,
        ft_DLClassCode_LR_From = 601,
        ft_DLClassCode_LR_To = 602,
        ft_DLClassCode_LR_Notes = 603,
        ft_DLClassCode_MR_From = 604,
        ft_DLClassCode_MR_To = 605,
        ft_DLClassCode_MR_Notes = 606,
        ft_DLClassCode_HR_From = 607,
        ft_DLClassCode_HR_To = 608,
        ft_DLClassCode_HR_Notes = 609,
        ft_DLClassCode_HC_From = 610,
        ft_DLClassCode_HC_To = 611,
        ft_DLClassCode_HC_Notes = 612,
        ft_DLClassCode_MC_From = 613,
        ft_DLClassCode_MC_To = 614,
        ft_DLClassCode_MC_Notes = 615,
        ft_DLClassCode_RE_From = 616,
        ft_DLClassCode_RE_To = 617,
        ft_DLClassCode_RE_Notes = 618,
        ft_DLClassCode_R_From = 619,
        ft_DLClassCode_R_To = 620,
        ft_DLClassCode_R_Notes = 621,
        ft_DLClassCode_CA_From = 622,
        ft_DLClassCode_CA_To = 623,
        ft_DLClassCode_CA_Notes = 624,

**Comment by hleb-albau** [comment]
еще бы описания какие-то(кроме dlclasscode)
