### ISSUE TITLE
add processParam.imageQA.angleThreshold and processParam.imageQA.dpiThreshold into request

### ISSUE THREAD

**Issue by ikliashchou** [regulaforensics/DocumentReader-web-openapi#52]
**processParam.imageQA.dpiThreshold**
number

this parameter sets threshold for Image QA check of the presented document physical dpi. If actual document dpi is below this threshold, check will fail. If not set, defaults to 150.

**processParam.imageQA.angleThreshold**
number

this parameter sets threshold for Image QA check of the presented document perspective angle in degrees. If actual document perspective angle is above this threshold, check will fail. If not set, defaults to 5.

**Comment by alshund** [comment]
Такой вопрос, при конвертации pdf -> jpg указываем значение dpi = 300. Что, если при передачи pdf в processParam.imageQA.dpiThreshold будет указано значение больше 300?

**Comment by alshund** [comment]
Нам стоит задавать imageQA? Либо, если DocumentReader не обнаружит imageQA, она определит значения dpiThreshold и angleThreshold по умолчанию?
